// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzn6YZJAAPo-F-4i4Lr4xR4mLs2XxNDsw',
    appId: '1:753406332510:web:93155222d689a577feeecf',
    messagingSenderId: '753406332510',
    projectId: 'numeretti-dottore-7c291',
    authDomain: 'numeretti-dottore-7c291.firebaseapp.com',
    databaseURL: 'https://numeretti-dottore-7c291-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numeretti-dottore-7c291.firebasestorage.app',
    measurementId: 'G-MG8GSB3T9N',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDABnnDZt50cJXCZHBadzQwHiWxTwevgEA',
    appId: '1:753406332510:ios:a8b24381b5609ba4feeecf',
    messagingSenderId: '753406332510',
    projectId: 'numeretti-dottore-7c291',
    databaseURL: 'https://numeretti-dottore-7c291-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numeretti-dottore-7c291.firebasestorage.app',
    iosBundleId: 'com.example.numerettiDottore',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDABnnDZt50cJXCZHBadzQwHiWxTwevgEA',
    appId: '1:753406332510:ios:a8b24381b5609ba4feeecf',
    messagingSenderId: '753406332510',
    projectId: 'numeretti-dottore-7c291',
    databaseURL: 'https://numeretti-dottore-7c291-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'numeretti-dottore-7c291.firebasestorage.app',
    iosBundleId: 'com.example.numerettiDottore',
  );
}
